### ISSUE TITLE
Incompatibilty with Minimum Stone by Fuzs

### ISSUE THREAD

**Issue by Afrocntrik** [Soulphur0/ElytraAeronautics#8]
[Crash Log](https://github.com/Soulphur0/ElytraAeronautics/files/12391079/crash-2023-08-20_22.43.03-client.txt) crash on startup. Incompatibility with [Minimum Stone's](https://modrinth.com/mod/minium-stone) rendering

---- Minecraft Crash Report ---- 
// My bad. 
 
Time: 2023-08-20 22:43:03 
Description: Initializing game 
 
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'miniumstone'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed
	at fuzs.miniumstone.client.MiniumStoneClient.registerHandlers(MiniumStoneClient.java:32)
	at fuzs.miniumstone.client.MiniumStoneClient.onConstructMod(MiniumStoneClient.java:26)
	at fuzs.puzzleslib.impl.client.core.FabricClientModConstructor.construct(FabricClientModConstructor.java:38)
	at fuzs.puzzleslib.impl.client.core.FabricClientFactories.constructClientMod(FabricClientFactories.java:18)
	at fuzs.puzzleslib.api.client.core.v1.ClientModConstructor.lambda$construct$0(ClientModConstructor.java:50)
	at fuzs.puzzleslib.impl.core.ModContext.scheduleClientModConstruction(ModContext.java:72)
	at fuzs.puzzleslib.api.client.core.v1.ClientModConstructor.construct(ClientModConstructor.java:46)
	at fuzs.miniumstone.client.MiniumStoneFabricClient.onInitializeClient(MiniumStoneFabricClient.java:11)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
 
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 16 more
 
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 20 more
 
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [elytraaeronautics.mixins.json:WorldRendererMixin from mod elytra_aeronautics] from phase [DEFAULT] in config [elytraaeronautics.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 23 more
 
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_761::ean_captureCloudRenderLocals with priority 1000 cannot inject into net/minecraft/class_761::method_3259(Lnet/minecraft/class_4587;Lorg/joml/Matrix4f;FDDD)V merged by me.jellysquid.mods.sodium.mixin.features.render.world.clouds.WorldRendererMixin with priority 1000 [PREINJECT Applicator Phase -> elytraaeronautics.mixins.json:WorldRendererMixin from mod elytra_aeronautics -> Prepare Injections ->  -> args$big000$elytra_aeronautics$ean_captureCloudRenderLocals(Lorg/spongepowered/asm/mixin/injection/invoke/arg/Args;)V -> Prepare]
 
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 23 more

**Comment by Soulphur0** [comment]
> [Crash Log](https://github.com/Soulphur0/ElytraAeronautics/files/12391079/crash-2023-08-20_22.43.03-client.txt) crash on startup. Incompatibility with [Minimum Stone's](https://modrinth.com/mod/minium-stone) rendering
> 
> ---- Minecraft Crash Report ---- // My bad.
> 
> Time: 2023-08-20 22:43:03 Description: Initializing game
> 
> java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'miniumstone'! at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) at net.minecraft.class_310.(class_310.java:458) at net.minecraft.client.main.Main.main(Main.java:211) at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed at fuzs.miniumstone.client.MiniumStoneClient.registerHandlers(MiniumStoneClient.java:32) at fuzs.miniumstone.client.MiniumStoneClient.onConstructMod(MiniumStoneClient.java:26) at fuzs.puzzleslib.impl.client.core.FabricClientModConstructor.construct(FabricClientModConstructor.java:38) at fuzs.puzzleslib.impl.client.core.FabricClientFactories.constructClientMod(FabricClientFactories.java:18) at fuzs.puzzleslib.api.client.core.v1.ClientModConstructor.lambda$construct$0(ClientModConstructor.java:50) at fuzs.puzzleslib.impl.core.ModContext.scheduleClientModConstruction(ModContext.java:72) at fuzs.puzzleslib.api.client.core.v1.ClientModConstructor.construct(ClientModConstructor.java:46) at fuzs.miniumstone.client.MiniumStoneFabricClient.onInitializeClient(MiniumStoneFabricClient.java:11) at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ... 7 more
> 
> Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ... 16 more
> 
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ... 20 more
> 
> Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [elytraaeronautics.mixins.json:WorldRendererMixin from mod elytra_aeronautics] from phase [DEFAULT] in config [elytraaeronautics.mixins.json] FAILED during APPLY at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ... 23 more
> 
> Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @at("INVOKE") on net/minecraft/class_761::ean_captureCloudRenderLocals with priority 1000 cannot inject into net/minecraft/class_761::method_3259(Lnet/minecraft/class_4587;Lorg/joml/Matrix4f;FDDD)V merged by me.jellysquid.mods.sodium.mixin.features.render.world.clouds.WorldRendererMixin with priority 1000 [PREINJECT Applicator Phase -> elytraaeronautics.mixins.json:WorldRendererMixin from mod elytra_aeronautics -> Prepare Injections -> -> args$big000$elytra_aeronautics$ean_captureCloudRenderLocals(Lorg/spongepowered/asm/mixin/injection/invoke/arg/Args;)V -> Prepare]
> 
> ```
> at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
> at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
> at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
> at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
> at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
> at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
> at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
> at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
> at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
> at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
> ... 23 more
> ```

Hey! Could you tell me the game version you are playing in? Is it 1.20.1? I got a last-minute issue regarding that version and I updated the file for the mod, in case it is a different version I can apply the same fix to them, if it is 1.20.1, try downloading the mod again and trying the new file, if the error still happens let me know.

**Comment by Afrocntrik** [comment]
Yes that did the trick!
